-- PostgreSQL bootstrap schema for fvpAdminBackend
-- Run this after creating the database `agrib2b`.
-- Example:
--   createdb agrib2b
--   psql -d agrib2b -f schema-bootstrap.sql

CREATE SCHEMA IF NOT EXISTS agrib2b;
SET search_path TO agrib2b, public;

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    company_name VARCHAR(180) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(40) NOT NULL,
    delivery_address VARCHAR(400) NOT NULL,
    city VARCHAR(120) NOT NULL,
    state VARCHAR(120) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255),
    auth_provider VARCHAR(30) NOT NULL,
    google_subject VARCHAR(255),
    email_verified BOOLEAN NOT NULL,
    preferred_payment_method VARCHAR(40),
    preferred_payment_handle VARCHAR(120),
    active BOOLEAN NOT NULL,
    deferred_payment_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    label VARCHAR(60) NOT NULL,
    recipient_name VARCHAR(160) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    line1 VARCHAR(400) NOT NULL,
    line2 VARCHAR(400),
    city VARCHAR(120) NOT NULL,
    state VARCHAR(120) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(120) NOT NULL,
    is_default BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_customer_address_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE IF NOT EXISTS app_document (
    id UUID PRIMARY KEY,
    original_file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(800) NOT NULL UNIQUE,
    path VARCHAR(800) NOT NULL UNIQUE,
    content_type VARCHAR(120),
    size_bytes BIGINT,
    checksum_sha256 VARCHAR(128),
    module VARCHAR(80) NOT NULL,
    owner_id BIGINT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inquiry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_type VARCHAR(20),
    reference_id VARCHAR(40) UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    alternate_phone VARCHAR(40),
    father_name VARCHAR(120),
    aadhaar_number VARCHAR(40),
    pan_number VARCHAR(20),
    full_address VARCHAR(500),
    product_name VARCHAR(255) NOT NULL,
    message VARCHAR(1200) NOT NULL,
    investment_amount NUMERIC(14, 2),
    investment_date DATE,
    preferred_payment_mode VARCHAR(80),
    transaction_id VARCHAR(120),
    payment_date DATE,
    farming_type VARCHAR(80),
    land_area VARCHAR(80),
    main_crops VARCHAR(255),
    irrigation_type VARCHAR(80),
    bank_account_number VARCHAR(40),
    ifsc_code VARCHAR(20),
    village VARCHAR(160),
    district VARCHAR(160),
    farmer_state VARCHAR(120),
    pin_code VARCHAR(20),
    collection_hub_name VARCHAR(160),
    hub_storage_type VARCHAR(80),
    hub_capacity_mt NUMERIC(12, 2),
    hub_pickup_radius_km INTEGER,
    hub_operating_days VARCHAR(120),
    hub_code VARCHAR(40),
    id_proof_url VARCHAR(500),
    id_proof_document_id UUID,
    id_proof_metadata VARCHAR(1200),
    payment_screenshot_url VARCHAR(500),
    payment_screenshot_document_id UUID,
    payment_screenshot_metadata VARCHAR(1200),
    aadhaar_document_url VARCHAR(500),
    aadhaar_document_id UUID,
    aadhaar_document_metadata VARCHAR(1200),
    land_proof_document_url VARCHAR(500),
    land_proof_document_id UUID,
    land_proof_document_metadata VARCHAR(1200),
    bank_passbook_document_url VARCHAR(500),
    bank_passbook_document_id UUID,
    bank_passbook_document_metadata VARCHAR(1200),
    hub_document_url VARCHAR(500),
    hub_document_id UUID,
    hub_document_metadata VARCHAR(1200),
    terms_accepted BOOLEAN,
    agreement_id VARCHAR(40),
    committed_return_amount NUMERIC(14, 2),
    farmer_action_note VARCHAR(1200),
    hub_action_note VARCHAR(1200),
    verification_status VARCHAR(20),
    payment_status VARCHAR(20),
    source VARCHAR(80) NOT NULL,
    admin_notes VARCHAR(1200),
    assigned_to VARCHAR(120),
    converted_lead_id BIGINT,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_inquiry_id_proof_document FOREIGN KEY (id_proof_document_id) REFERENCES app_document(id),
    CONSTRAINT fk_inquiry_payment_screenshot_document FOREIGN KEY (payment_screenshot_document_id) REFERENCES app_document(id),
    CONSTRAINT fk_inquiry_aadhaar_document FOREIGN KEY (aadhaar_document_id) REFERENCES app_document(id),
    CONSTRAINT fk_inquiry_land_proof_document FOREIGN KEY (land_proof_document_id) REFERENCES app_document(id),
    CONSTRAINT fk_inquiry_bank_passbook_document FOREIGN KEY (bank_passbook_document_id) REFERENCES app_document(id),
    CONSTRAINT fk_inquiry_hub_document FOREIGN KEY (hub_document_id) REFERENCES app_document(id)
);

CREATE TABLE IF NOT EXISTS lead (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    company_name VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    source VARCHAR(80) NOT NULL,
    notes VARCHAR(1200),
    assigned_to VARCHAR(120),
    inquiry_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(160) NOT NULL,
    email VARCHAR(160),
    phone VARCHAR(40),
    user_type VARCHAR(40) NOT NULL,
    source_inquiry_id BIGINT,
    password_hash VARCHAR(255),
    reset_password BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    activated_at TIMESTAMP,
    last_login_at TIMESTAMP,
    CONSTRAINT uk_portal_user_username UNIQUE (username),
    CONSTRAINT uk_portal_user_source_inquiry UNIQUE (source_inquiry_id)
);

CREATE TABLE IF NOT EXISTS portal_password_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    purpose VARCHAR(40) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_portal_password_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_portal_password_token_user FOREIGN KEY (portal_user_id) REFERENCES portal_user(id)
);

CREATE TABLE IF NOT EXISTS app_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(160) NOT NULL UNIQUE,
    category VARCHAR(80) NOT NULL,
    setting_value VARCHAR(4000),
    value_type VARCHAR(20) NOT NULL,
    secret BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    description VARCHAR(500),
    updated_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS smtpconfig (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    host VARCHAR(255),
    port INTEGER,
    username VARCHAR(255),
    password VARCHAR(1000),
    from_email VARCHAR(255),
    from_name VARCHAR(160),
    auth_enabled BOOLEAN NOT NULL,
    start_tls_enabled BOOLEAN NOT NULL,
    frontend_base_url VARCHAR(500),
    updated_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS investor_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_code VARCHAR(40) NOT NULL UNIQUE,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    source_inquiry_id BIGINT,
    status VARCHAR(30) NOT NULL,
    verification_status VARCHAR(20) NOT NULL,
    notes VARCHAR(1200),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS investment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_account_id BIGINT NOT NULL,
    investment_reference VARCHAR(40) NOT NULL UNIQUE,
    principal_amount NUMERIC(14, 2) NOT NULL,
    monthly_return_rate NUMERIC(5, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(1200),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_investment_investor_account FOREIGN KEY (investor_account_id) REFERENCES investor_account(id)
);

CREATE TABLE IF NOT EXISTS investor_payout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_account_id BIGINT NOT NULL,
    payout_reference VARCHAR(40) NOT NULL UNIQUE,
    total_amount NUMERIC(14, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_channel VARCHAR(80),
    transaction_reference VARCHAR(120),
    notes VARCHAR(1200),
    approved_by VARCHAR(120),
    approved_at TIMESTAMP,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_investor_payout_investor_account FOREIGN KEY (investor_account_id) REFERENCES investor_account(id)
);

CREATE TABLE IF NOT EXISTS investor_monthly_return (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_account_id BIGINT NOT NULL,
    investment_id BIGINT NOT NULL,
    payout_id BIGINT,
    period_year INTEGER NOT NULL,
    period_month INTEGER NOT NULL,
    base_principal NUMERIC(14, 2) NOT NULL,
    return_rate NUMERIC(5, 2) NOT NULL,
    calculated_amount NUMERIC(14, 2) NOT NULL,
    override_amount NUMERIC(14, 2),
    final_amount NUMERIC(14, 2) NOT NULL,
    override_reason VARCHAR(300),
    status VARCHAR(30) NOT NULL,
    submitted_by VARCHAR(120),
    submitted_at TIMESTAMP,
    approved_by VARCHAR(120),
    approved_at TIMESTAMP,
    notes VARCHAR(1200),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_investor_monthly_return_investor_account FOREIGN KEY (investor_account_id) REFERENCES investor_account(id),
    CONSTRAINT fk_investor_monthly_return_investment FOREIGN KEY (investment_id) REFERENCES investment(id),
    CONSTRAINT fk_investor_monthly_return_payout FOREIGN KEY (payout_id) REFERENCES investor_payout(id)
);

CREATE TABLE IF NOT EXISTS investor_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_id BIGINT NOT NULL,
    receipt_number VARCHAR(40) NOT NULL UNIQUE,
    document_url VARCHAR(500),
    version INTEGER NOT NULL,
    generated_by VARCHAR(120),
    generated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_investor_receipt_payout FOREIGN KEY (payout_id) REFERENCES investor_payout(id)
);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    sku VARCHAR(255) NOT NULL UNIQUE,
    price NUMERIC(12, 2),
    price_unit VARCHAR(30) NOT NULL,
    default_tax_rate NUMERIC(5, 2),
    default_discount_rate NUMERIC(5, 2),
    status VARCHAR(255) NOT NULL,
    image_url VARCHAR(600),
    image_document_id UUID,
    image_original_file_name VARCHAR(255),
    image_content_type VARCHAR(120),
    image_size_bytes BIGINT,
    short_description VARCHAR(300) NOT NULL,
    long_description VARCHAR(1200) NOT NULL,
    moq VARCHAR(255) NOT NULL,
    featured BOOLEAN NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_product_image_document FOREIGN KEY (image_document_id) REFERENCES app_document(id)
);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(160),
    first_name VARCHAR(80),
    last_name VARCHAR(80),
    email VARCHAR(255),
    phone VARCHAR(40),
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    role_id BIGINT,
    CONSTRAINT fk_app_user_role FOREIGN KEY (role_id) REFERENCES app_role(id)
);

CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    customer_id BIGINT,
    full_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    delivery_address VARCHAR(400) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    postal_code VARCHAR(255) NOT NULL,
    customer_notes VARCHAR(1600) NOT NULL,
    status VARCHAR(255) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    payment_method VARCHAR(40) NOT NULL DEFAULT 'ONLINE',
    payment_due_amount NUMERIC(12, 2),
    payment_due_at TIMESTAMP,
    payment_provider VARCHAR(80),
    payment_provider_order_id VARCHAR(140),
    payment_provider_reference VARCHAR(140),
    payment_collected_by VARCHAR(120),
    payment_collection_reference VARCHAR(140),
    cancellation_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
    cancellation_reason VARCHAR(600),
    cancellation_requested_by VARCHAR(120),
    cancellation_requested_at TIMESTAMP,
    cancellation_decision_note VARCHAR(600),
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    quoted_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    shipped_at TIMESTAMP,
    delivered_at TIMESTAMP,
    admin_notes VARCHAR(1400),
    quote_reference VARCHAR(120),
    subtotal_amount NUMERIC(12, 2),
    shipping_amount NUMERIC(12, 2),
    tax_amount NUMERIC(12, 2),
    discount_amount NUMERIC(12, 2),
    effective_tax_rate NUMERIC(5, 2),
    effective_discount_rate NUMERIC(5, 2),
    total_amount NUMERIC(12, 2),
    CONSTRAINT fk_purchase_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    product_id BIGINT,
    product_name VARCHAR(255) NOT NULL,
    product_slug VARCHAR(255),
    quantity INTEGER NOT NULL,
    unit VARCHAR(255) NOT NULL,
    moq_snapshot VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12, 2),
    line_total NUMERIC(12, 2),
    line_subtotal NUMERIC(12, 2),
    discount_rate NUMERIC(5, 2),
    discount_amount NUMERIC(12, 2),
    tax_rate NUMERIC(5, 2),
    tax_amount NUMERIC(12, 2),
    CONSTRAINT fk_order_item_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE IF NOT EXISTS order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    note VARCHAR(600) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_status_history_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id)
);

CREATE TABLE IF NOT EXISTS order_payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    provider_order_id VARCHAR(120),
    provider_reference VARCHAR(120),
    status VARCHAR(40),
    payload VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_payment_event_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id)
);

CREATE TABLE IF NOT EXISTS order_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    refund_id VARCHAR(40) NOT NULL,
    provider_refund_id VARCHAR(140),
    provider_payment_id VARCHAR(140),
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    refund_method VARCHAR(30) NOT NULL DEFAULT 'CASHFREE',
    status VARCHAR(30) NOT NULL,
    speed VARCHAR(20) NOT NULL,
    note VARCHAR(100) NOT NULL,
    status_description VARCHAR(500),
    refund_arn VARCHAR(140),
    requested_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    CONSTRAINT fk_order_refund_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    CONSTRAINT uk_order_refund_refund_id UNIQUE (refund_id),
    CONSTRAINT uk_order_refund_provider_refund_id UNIQUE (provider_refund_id),
    CONSTRAINT ck_order_refund_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_product_category_id ON product(category_id);
CREATE INDEX IF NOT EXISTS idx_product_image_document_id ON product(image_document_id);
CREATE INDEX IF NOT EXISTS idx_customer_address_customer_id ON customer_address(customer_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_customer_id ON purchase_order(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_item_purchase_order_id ON order_item(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product_id ON order_item(product_id);
CREATE INDEX IF NOT EXISTS idx_order_status_history_purchase_order_id ON order_status_history(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_order_payment_event_purchase_order_id ON order_payment_event(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_order_refund_purchase_order ON order_refund(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_portal_password_token_portal_user_id ON portal_password_token(portal_user_id);
CREATE INDEX IF NOT EXISTS idx_investment_investor_account_id ON investment(investor_account_id);
CREATE INDEX IF NOT EXISTS idx_investor_payout_investor_account_id ON investor_payout(investor_account_id);
CREATE INDEX IF NOT EXISTS idx_investor_monthly_return_investor_account_id ON investor_monthly_return(investor_account_id);
CREATE INDEX IF NOT EXISTS idx_investor_monthly_return_investment_id ON investor_monthly_return(investment_id);
CREATE INDEX IF NOT EXISTS idx_investor_monthly_return_payout_id ON investor_monthly_return(payout_id);
CREATE INDEX IF NOT EXISTS idx_investor_receipt_payout_id ON investor_receipt(payout_id);

INSERT INTO app_role (code, name, description)
VALUES
    ('ADMIN', 'Administrator', 'Administrative user'),
    ('SYSADMIN', 'System Administrator', 'System-level administrative user'),
    ('SALES', 'Sales', 'Sales team user')
ON CONFLICT (code) DO NOTHING;
