spring.application.name=agri-b2b-backend
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/agrib2b?currentSchema=agrib2b}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ajeet157}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=agrib2b

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=agrib2b

app.security.jwt.secret=${JWT_SECRET:replace-this-secret-in-production-with-at-least-32-characters}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.upload.base-dir=${APP_UPLOAD_DIR:uploads}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
