CREATE TABLE IF NOT EXISTS order_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    refund_id VARCHAR(40) NOT NULL,
    provider_refund_id VARCHAR(140),
    provider_payment_id VARCHAR(140),
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    speed VARCHAR(20) NOT NULL,
    note VARCHAR(100) NOT NULL,
    status_description VARCHAR(500),
    refund_arn VARCHAR(140),
    requested_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    CONSTRAINT fk_order_refund_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (id),
    CONSTRAINT uk_order_refund_refund_id UNIQUE (refund_id),
    CONSTRAINT uk_order_refund_provider_refund_id UNIQUE (provider_refund_id),
    CONSTRAINT ck_order_refund_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_refund_purchase_order
    ON order_refund (purchase_order_id);
