package com.agriplatform.backend.inquiry.dto;

import com.agriplatform.backend.*;
import com.agriplatform.backend.auth.controller.*;
import com.agriplatform.backend.auth.dto.*;
import com.agriplatform.backend.auth.service.*;
import com.agriplatform.backend.category.controller.*;
import com.agriplatform.backend.category.model.*;
import com.agriplatform.backend.category.repository.*;
import com.agriplatform.backend.common.controller.*;
import com.agriplatform.backend.config.*;
import com.agriplatform.backend.customer.controller.*;
import com.agriplatform.backend.customer.dto.*;
import com.agriplatform.backend.customer.model.*;
import com.agriplatform.backend.customer.repository.*;
import com.agriplatform.backend.customer.service.*;
import com.agriplatform.backend.document.controller.*;
import com.agriplatform.backend.document.dto.*;
import com.agriplatform.backend.document.model.*;
import com.agriplatform.backend.document.repository.*;
import com.agriplatform.backend.document.service.*;
import com.agriplatform.backend.inquiry.controller.*;
import com.agriplatform.backend.inquiry.dto.*;
import com.agriplatform.backend.inquiry.model.*;
import com.agriplatform.backend.inquiry.repository.*;
import com.agriplatform.backend.inquiry.service.*;
import com.agriplatform.backend.investor.controller.*;
import com.agriplatform.backend.investor.dto.*;
import com.agriplatform.backend.investor.model.*;
import com.agriplatform.backend.investor.repository.*;
import com.agriplatform.backend.investor.service.*;
import com.agriplatform.backend.lead.controller.*;
import com.agriplatform.backend.lead.dto.*;
import com.agriplatform.backend.lead.model.*;
import com.agriplatform.backend.lead.repository.*;
import com.agriplatform.backend.lead.service.*;
import com.agriplatform.backend.order.controller.*;
import com.agriplatform.backend.order.dto.*;
import com.agriplatform.backend.order.model.*;
import com.agriplatform.backend.order.repository.*;
import com.agriplatform.backend.order.service.*;
import com.agriplatform.backend.portal.controller.*;
import com.agriplatform.backend.portal.dto.*;
import com.agriplatform.backend.portal.model.*;
import com.agriplatform.backend.portal.repository.*;
import com.agriplatform.backend.portal.service.*;
import com.agriplatform.backend.product.controller.*;
import com.agriplatform.backend.product.dto.*;
import com.agriplatform.backend.product.model.*;
import com.agriplatform.backend.product.repository.*;
import com.agriplatform.backend.product.service.*;
import com.agriplatform.backend.security.*;
import com.agriplatform.backend.user.controller.*;
import com.agriplatform.backend.user.dto.*;
import com.agriplatform.backend.user.model.*;
import com.agriplatform.backend.user.repository.*;
import com.agriplatform.backend.user.service.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public record InquiryResponse(
        Long id,
        String inquiryType,
        String referenceId,
        String fullName,
        String companyName,
        String email,
        String phone,
        String alternatePhone,
        String fatherName,
        String aadhaarNumber,
        String panNumber,
        String fullAddress,
        String productName,
        String message,
        BigDecimal investmentAmount,
        LocalDate investmentDate,
        String preferredPaymentMode,
        String transactionId,
        LocalDate paymentDate,
        String farmingType,
        String landArea,
        String mainCrops,
        String irrigationType,
        String bankAccountNumber,
        String ifscCode,
        String village,
        String district,
        String farmerState,
        String pinCode,
        String collectionHubName,
        String hubStorageType,
        BigDecimal hubCapacityMt,
        Integer hubPickupRadiusKm,
        String hubOperatingDays,
        String hubCode,
        String idProofUrl,
        String idProofMetadata,
        String paymentScreenshotUrl,
        String paymentScreenshotMetadata,
        String aadhaarDocumentUrl,
        String aadhaarDocumentMetadata,
        String landProofDocumentUrl,
        String landProofDocumentMetadata,
        String bankPassbookDocumentUrl,
        String bankPassbookDocumentMetadata,
        String hubDocumentUrl,
        String hubDocumentMetadata,
        Boolean termsAccepted,
        String agreementId,
        BigDecimal committedReturnAmount,
        String farmerActionNote,
        String hubActionNote,
        String verificationStatus,
        String paymentStatus,
        String source,
        String adminNotes,
        String assignedTo,
        Long convertedLeadId,
        String status,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {
}
